"use client";

import { useEffect, useRef, useState } from "react";
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { Activity, ArrowDown, ArrowUp, Check, ChevronDown, GripVertical, LayoutDashboard, Maximize2, Pencil, RefreshCw, Sparkles, Star, Undo2, X } from "lucide-react";
import { definitions, filterAndGroup, sampleData, surfaces, breakdownRows, snapshotIds, mergeSavedOrder, type Definition } from "./sample-data";
import { BreakdownChart } from "./breakdown-chart";
import "./analytics.css";

const initialOrder = definitions.map(card => card.id);
type CardId = typeof initialOrder[number];
interface Layout { order: CardId[]; wide: string[]; favourites: string[] }
const defaults: Layout = { order: initialOrder, wide: [], favourites: ["turns"] };
const dateLabel = (date: string) => new Date(`${date}T00:00:00Z`).toLocaleDateString("en-US", { month: "short", day: "numeric", timeZone: "UTC" });
function ChartCard({ definition: d, from, to, group, favourite, toggleFavourite, editing, wide, resize, move, expand }: { definition: Definition; from: string; to: string; group: string; favourite: boolean; toggleFavourite: () => void; editing: boolean; wide: boolean; resize: () => void; move: (delta: number) => void; expand: () => void }) {
  const [breakdown, setBreakdown] = useState("model"), [hidden, setHidden] = useState<string[]>([]), [range, setRange] = useState("global");
  const series = d.id === "turns" && breakdown === "surface" ? surfaces : d.series;
  const daily = filterAndGroup(sampleData(d.id, series), range === "7" ? "2026-08-30" : from, range === "7" ? "2026-09-05" : to, "day");
  const data = filterAndGroup(daily, "0000-01-01", "9999-12-31", group, d.id === "performance" || d.id === "usage");
  const isBreakdown = ["donut", "ranking", "segmented", "progress", "gauge", "metrics"].includes(d.kind);
  const rows = breakdownRows(d, daily).filter(row => !hidden.includes(row.name));
  const visible = series.filter(name => !hidden.includes(name));
  const total = daily.reduce((sum, row) => sum + visible.reduce((n, key) => n + Number(row[key]), 0), 0);
  const Chart = (d.kind === "bar" || d.kind === "grouped") ? BarChart : d.kind === "line" ? LineChart : AreaChart;
  return <>
    {editing && <div className="preview-edit-tools"><GripVertical size={15} /><span>Drag to arrange</span><button aria-label={`Move ${d.title} earlier`} onClick={() => move(-1)}><ArrowUp size={15} /></button><button aria-label={`Move ${d.title} later`} onClick={() => move(1)}><ArrowDown size={15} /></button><button onClick={resize}>{wide ? "Half width" : "Full width"}</button></div>}
    <div className="analytics-card-header"><div><h2><button onClick={expand}>{d.title}</button></h2><p>{d.subtitle}</p><small>SAMPLE DATA · AUG 7 – SEP 5, 2026</small></div><div className="analytics-card-actions"><button aria-label={`${favourite ? "Unfavourite" : "Favourite"} ${d.title}`} aria-pressed={favourite} onClick={toggleFavourite}><Star size={16} fill={favourite ? "currentColor" : "none"} className={favourite ? "favourited" : ""} /></button><select aria-label={`${d.title} date range`} value={range} onChange={event => setRange(event.target.value)}><option value="global">Global range</option><option value="7">Last 7 days</option></select><button aria-label={`Expand ${d.title}`} onClick={expand}><Maximize2 size={14} /></button></div></div>
    {!isBreakdown && <div className="analytics-metric"><div><small>{d.id === "usage" ? "AVERAGE DAILY USAGE" : d.id === "performance" ? "AVERAGE LCP" : "TOTAL"}</small><strong>{d.id === "performance" ? (total / Math.max(1, daily.length * visible.length)).toFixed(2) + "s" : d.id === "usage" ? (total / Math.max(1, daily.length)).toFixed(0) + "%" : total.toLocaleString("en-US")}</strong></div>{d.id === "turns" && <div className="analytics-segment" role="group" aria-label="Turns breakdown">{["model", "surface"].map(value => <button key={value} aria-pressed={breakdown === value} onClick={() => { setBreakdown(value); setHidden([]); }}>By {value}</button>)}</div>}</div>}
    {isBreakdown ? <><p className="breakdown-period">{snapshotIds.has(d.id) ? `Snapshot · ${daily.length ? dateLabel(daily.at(-1)!.date) : "no data in range"}` : "Totals for selected date range"}</p>{daily.length ? <BreakdownChart definition={d} rows={rows} /> : <p className="analytics-empty">No sample measurements in this date range.</p>}</> : data.length ? <div className="analytics-plot"><ResponsiveContainer width="100%" height="100%" minWidth={0}><Chart data={data} margin={{ top: 14, right: 8, bottom: 0, left: -22 }} accessibilityLayer><CartesianGrid vertical={false} stroke="var(--border)" strokeDasharray="3 3" /><XAxis dataKey="date" tickFormatter={dateLabel} axisLine={false} tickLine={false} minTickGap={45} tick={{ fill: "var(--muted-foreground)", fontSize: 10 }} /><YAxis domain={d.id === "usage" ? [0, 100] : [0, "auto"]} tickFormatter={value => d.id === "usage" ? `${value}%` : String(value)} axisLine={false} tickLine={false} tick={{ fill: "var(--muted-foreground)", fontSize: 10 }} /><Tooltip labelFormatter={label => dateLabel(String(label))} contentStyle={{ background: "var(--card)", border: "1px solid var(--border)", borderRadius: 10, fontSize: 12, color: "var(--foreground)" }} />{series.map((name, index) => { const props = { dataKey: name, name, hide: hidden.includes(name), stroke: d.colors[index % d.colors.length], fill: d.colors[index % d.colors.length], isAnimationActive: false }; return (d.kind === "bar" || d.kind === "grouped") ? <Bar key={name} {...props} stackId={d.kind === "bar" ? "usage" : undefined} maxBarSize={28} /> : d.kind === "line" ? <Line key={name} {...props} type="monotone" dot={false} strokeWidth={2} /> : <Area key={name} {...props} stackId="activity" type="monotone" fillOpacity={.9} strokeWidth={1.5} />; })}</Chart></ResponsiveContainer></div> : <p className="analytics-empty">No sample measurements in this date range.</p>}
    <div className="analytics-legend" aria-label={`${d.title} legend`}>{series.map((name, index) => <button key={name} aria-pressed={!hidden.includes(name)} onClick={() => setHidden(previous => previous.includes(name) ? previous.filter(item => item !== name) : [...previous, name])}><i style={{ background: d.colors[index % d.colors.length] }} />{name}</button>)}</div>
  </>;
}
export function AnalyticsPreview({ homeHref = "/preview" }: { homeHref?: string }) {
  const [layout, setLayout] = useState<Layout>(defaults), [undo, setUndo] = useState<Layout[]>([]), [loaded, setLoaded] = useState(false), [notice, setNotice] = useState("");
  const [category, setCategory] = useState("All"), [range, setRange] = useState("30"), [group, setGroup] = useState("day"), [editing, setEditing] = useState(false), [summary, setSummary] = useState(true), [expanded, setExpanded] = useState<CardId | null>(null);
  const [from, setFrom] = useState("2026-08-07"), [to, setTo] = useState("2026-09-05");
  const dragged = useRef<CardId | null>(null), modal = useRef<HTMLDialogElement>(null);
  useEffect(() => { let cancelled = false; queueMicrotask(() => { if (cancelled) return; try { const saved = JSON.parse(localStorage.getItem("atlas-analytics-preview-v1") ?? "null"); if (saved && Array.isArray(saved.order) && saved.order.length <= initialOrder.length && new Set(saved.order).size === saved.order.length && saved.order.every((id: CardId) => initialOrder.includes(id)) && Array.isArray(saved.wide) && saved.wide.every((id: CardId) => initialOrder.includes(id)) && Array.isArray(saved.favourites) && saved.favourites.every((id: CardId) => initialOrder.includes(id))) setLayout({ ...saved, order: mergeSavedOrder(saved.order, initialOrder) as CardId[] }); } catch { setNotice("Saved layout could not be read. Using the default arrangement."); } setLoaded(true); }); return () => { cancelled = true; }; }, []);
  useEffect(() => { if (loaded) try { localStorage.setItem("atlas-analytics-preview-v1", JSON.stringify(layout)); } catch { queueMicrotask(() => setNotice("Browser storage is unavailable. Changes remain in this session.")); } }, [layout, loaded]);
  function update(next: Layout) { setUndo(previous => [...previous.slice(-19), layout]); setLayout(next); }
  function reorder(id: CardId, target: number) { const order = layout.order.filter(item => item !== id); order.splice(Math.max(0, Math.min(order.length, target)), 0, id); update({ ...layout, order }); }
  function toggle(key: "wide" | "favourites", id: CardId) { update({ ...layout, [key]: layout[key].includes(id) ? layout[key].filter(item => item !== id) : [...layout[key], id] }); }
  function cardProps(d: Definition) { return { definition: d, from: range === "7" ? "2026-08-30" : range === "30" ? "2026-08-07" : from, to: range === "custom" ? to : "2026-09-05", group, favourite: layout.favourites.includes(d.id), toggleFavourite: () => toggle("favourites", d.id), editing, wide: layout.wide.includes(d.id), resize: () => toggle("wide", d.id), move: (delta: number) => reorder(d.id, layout.order.indexOf(d.id) + delta), expand: () => { setExpanded(d.id); modal.current?.showModal(); } }; }
  const shown = layout.order.map(id => definitions.find(d => d.id === id)!).filter(d => category === "All" || (category === "Favourites" ? layout.favourites.includes(d.id) : d.category === category));
  return <main id="main-content" className="analytics-preview" tabIndex={-1}>
    <aside className="analytics-sidebar"><a href={homeHref} className="analytics-brand"><Activity size={24} />Atlas <span> / admin</span></a><div className="analytics-nav"><LayoutDashboard size={17} />Dashboard</div><small>WORKSPACE</small>{["All", "AI usage", "Engineering", "Audience", "Community", "Events", "Favourites"].map(item => <button key={item} aria-pressed={category === item} onClick={() => setCategory(item)}>{item === "Favourites" ? <Star size={16} /> : <Activity size={16} />}{item}</button>)}<p>Local test dashboard<br /><span>Synthetic data · saved in this browser</span></p></aside>
    <div className="analytics-main"><header className="analytics-heading"><div><h1>Dashboard</h1><p>Site health, audience, and AI activity.</p></div><span className="preview-badge">Local preview · sample data</span></header>
      <div className="analytics-toolbar"><div className="analytics-filters">{["Favourites", "All", "AI usage", "Engineering", "Audience", "Community", "Events"].map(item => <button key={item} aria-pressed={category === item} onClick={() => setCategory(item)}>{item === "Favourites" && <Star size={13} />}{item}</button>)}</div><div className="analytics-controls"><select aria-label="Dashboard date range" value={range} onChange={event => setRange(event.target.value)}><option value="7">Last 7 days</option><option value="30">Last 30 days</option><option value="custom">Custom range</option></select><select aria-label="Group charts by" value={group} onChange={event => setGroup(event.target.value)}><option value="day">Daily</option><option value="week">Weekly</option></select><button aria-pressed={editing} onClick={() => setEditing(!editing)}>{editing ? <Check size={15} /> : <Pencil size={15} />}{editing ? "Done" : "Edit"}</button></div></div>
      {range === "custom" && <div className="analytics-custom"><label>From <input type="date" aria-label="From date" value={from} max={to} onInput={event => setFrom(event.currentTarget.value)} onChange={event => setFrom(event.target.value)} /></label><label>To <input type="date" aria-label="To date" min={from} value={to} onInput={event => setTo(event.currentTarget.value)} onChange={event => setTo(event.target.value)} /></label></div>}
      {editing && <div className="analytics-edit-bar"><span>Drag cards to reorder, or use the arrow buttons. Choose full or half width.</span><button disabled={!undo.length} onClick={() => { setLayout(undo[undo.length - 1]); setUndo(undo.slice(0, -1)); }}><Undo2 size={15} />Undo</button><button onClick={() => update(defaults)}><RefreshCw size={15} />Reset layout</button></div>}
      <section className="analytics-summary"><button className="analytics-summary-toggle" aria-expanded={summary} onClick={() => setSummary(!summary)}><span><Sparkles size={15} />Summary</span><ChevronDown size={15} /></button>{summary && <div className="analytics-summary-body"><div><small>CHARTS</small><strong>{shown.length}</strong></div><div><small>DATE RANGE</small><strong>{range === "7" ? "7 days" : range === "30" ? "30 days" : "Custom"}</strong></div><div><small>RESOLUTION</small><strong>{group === "day" ? "Daily" : "Weekly"}</strong></div><p>Explore the charts below. Click a legend to show or hide a series.<br />Sample dates: August 7 – September 5, 2026.</p></div>}</section>
      {notice && <p role="status">{notice}</p>}
      <div className="analytics-grid">{shown.map(d => <article key={d.id} className={`analytics-card ${layout.wide.includes(d.id) ? "wide" : ""} ${editing ? "editing" : ""}`} draggable={editing} onDragStart={event => { if ((event.target as HTMLElement).closest("button,select,input")) { event.preventDefault(); return; } dragged.current = d.id; }} onDragOver={event => { if (editing) event.preventDefault(); }} onDragEnd={() => { dragged.current = null; }} onDrop={event => { event.preventDefault(); if (dragged.current) reorder(dragged.current, layout.order.indexOf(d.id)); dragged.current = null; }}><ChartCard {...cardProps(d)} /></article>)}</div>
      {!shown.length && <p className="analytics-empty">No favourites yet. Star a chart to keep it here.</p>}
    </div><dialog ref={modal} className="analytics-modal" aria-label="Expanded chart" onCancel={() => setExpanded(null)}><button className="analytics-modal-close" aria-label="Close expanded chart" onClick={() => { modal.current?.close(); setExpanded(null); }}><X size={20} /></button>{expanded && <ChartCard {...cardProps(definitions.find(d => d.id === expanded)!)} editing={false} />}</dialog>
  </main>;
}
